### ISSUE TITLE
Escrever sobre reuso: Composição e Herança

### ISSUE THREAD

**Issue by eduardolfalcao** [eduardolfalcao/POO-Unifacisa#11]

**Comment by Luan-Augusto** [comment]
E ai Professor to enviando aqui esse cod que fiz relacionado a herança e queria que o senhor comentasse sobre ele em nossa aula de sexta-feira se possível. Valeu!

[Projeto-Heranca.zip](https://github.com/eduardolfalcao/POO-Unifacisa/files/4325542/Projeto-Heranca.zip)

**Comment by eduardolfalcao** [comment]
> E ai Professor to enviando aqui esse cod que fiz relacionado a herança e queria que o senhor comentasse sobre ele em nossa aula de sexta-feira se possível. Valeu!
> 
> [Projeto-Heranca.zip](https://github.com/eduardolfalcao/POO-Unifacisa/files/4325542/Projeto-Heranca.zip)

Fala Luan. Ficou legal. Só o atributo funcionario dentro da classe Funcionario que ficou um pouco estranho.

Sugestão: pratica a sobrescrita... primeiro cria a função calculaBonificacao() em Funcionario, depois cria sub-classes de Funcionario, e depois sobrecreve calculaBonificacao() nas sub-classes.
